definitions:
  dto.DepositRequest:
    properties:
      amount:
        type: number
      currency:
        type: string
    required:
    - amount
    - currency
    type: object
  dto.DepositResponse:
    properties:
      message:
        type: string
      new_balance:
        $ref: '#/definitions/pkg.AccountWallets'
    type: object
  dto.GetWalletsResponse:
    properties:
      balance:
        $ref: '#/definitions/pkg.AccountWallets'
    type: object
  dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.Message:
    properties:
      message:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  pkg.AccountWallets:
    additionalProperties:
      format: float32
      type: number
    type: object
info:
  contact: {}
paths:
  /api/v1/balance:
    get:
      consumes:
      - application/json
      description: Возвращает список кошельков и их балансы для авторизованного пользователя.
      produces:
      - application/json
      responses:
        "200":
          description: User wallets
          schema:
            $ref: '#/definitions/dto.GetWalletsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Message'
      security:
      - BearerAuth: []
      summary: Получение кошельков пользователя
      tags:
      - wallet
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя. При успешной авторизации возвращается
        JWT-токен.
      parameters:
      - description: User login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT-token
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "401":
          description: Invalid username or password
          schema:
            $ref: '#/definitions/dto.Message'
      summary: Авторизация пользователя
      tags:
      - auth
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя.
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/dto.Message'
        "400":
          description: Username or email already exists
          schema:
            $ref: '#/definitions/dto.Message'
      summary: Регистрация пользователя
      tags:
      - auth
  /api/v1/wallet/deposit:
    post:
      consumes:
      - application/json
      description: Позволяет пользователю пополнить свой счет. Проверяется корректность
        суммы и валюты.
      parameters:
      - description: Сумма и валюта для пополнения
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.DepositRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Account topped up successfully
          schema:
            $ref: '#/definitions/dto.DepositResponse'
        "400":
          description: Invalid amount or currency
          schema:
            $ref: '#/definitions/dto.Message'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Message'
      security:
      - BearerAuth: []
      summary: Пополнение счета пользователя
      tags:
      - wallet
swagger: "2.0"
